// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {domain} from '../models';

export function CreateAccount(arg1:string,arg2:string):Promise<bindings.AuthResult>;

export function GetMe(arg1:string):Promise<domain.UserResponse>;

export function Login(arg1:string,arg2:string):Promise<bindings.AuthResult>;

export function Logout(arg1:string):Promise<void>;
