// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAccount(arg1, arg2) {
  return window['go']['bindings']['AuthApp']['CreateAccount'](arg1, arg2);
}

export function GetMe(arg1) {
  return window['go']['bindings']['AuthApp']['GetMe'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['bindings']['AuthApp']['Login'](arg1, arg2);
}

export function Logout(arg1) {
  return window['go']['bindings']['AuthApp']['Logout'](arg1);
}
