// Automatically generated by Wails. DO NOT EDIT manually.
// Regenerated by `wails dev` or `wails build`.

export interface CategoryResponse {
  id: string;
  slug: string;
  name: string;
  emoji: string;
}

export interface QuestionResponse {
  id: string;
  category_id: string;
  text: string;
}

export interface VoteResultResponse {
  question_id: string;
  pct_preto: number;
  pct_branco: number;
  total: number;
}

export interface DayVotesEntry {
  question_id: string;
  text: string;
  votes_preto: number;
  votes_branco: number;
  total: number;
}

export function ListCategories(): Promise<CategoryResponse[]>;
export function RandomQuestions(limit: number): Promise<QuestionResponse[]>;
export function SubmitVote(questionID: string, choice: string): Promise<VoteResultResponse>;
export function TodayResults(): Promise<DayVotesEntry[]>;
