// @ts-check
// Automatically generated by Wails. DO NOT EDIT manually.
// Regenerated by `wails dev` or `wails build`.

export function ListCategories() {
  return window['go']['bindings']['GameApp']['ListCategories']();
}

export function RandomQuestions(limit) {
  return window['go']['bindings']['GameApp']['RandomQuestions'](limit);
}

export function SubmitVote(questionID, choice) {
  return window['go']['bindings']['GameApp']['SubmitVote'](questionID, choice);
}

export function TodayResults() {
  return window['go']['bindings']['GameApp']['TodayResults']();
}
