// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ListCategories():Promise<Array<domain.CategoryResponse>>;

export function RandomQuestions(arg1:number):Promise<Array<domain.QuestionResponse>>;

export function SubmitVote(arg1:string,arg2:string):Promise<domain.VoteResultResponse>;

export function TodayResults():Promise<Array<domain.DayVotesEntry>>;
