// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListCategories() {
  return window['go']['bindings']['GameApp']['ListCategories']();
}

export function RandomQuestions(arg1) {
  return window['go']['bindings']['GameApp']['RandomQuestions'](arg1);
}

export function SubmitVote(arg1, arg2) {
  return window['go']['bindings']['GameApp']['SubmitVote'](arg1, arg2);
}

export function TodayResults() {
  return window['go']['bindings']['GameApp']['TodayResults']();
}
