// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';

export function GetServerStatus():Promise<bindings.ServerStatus>;

export function StartTunnel():Promise<string>;

export function StopTunnel():Promise<void>;
