// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerStatus() {
  return window['go']['bindings']['ServerApp']['GetServerStatus']();
}

export function StartTunnel() {
  return window['go']['bindings']['ServerApp']['StartTunnel']();
}

export function StopTunnel() {
  return window['go']['bindings']['ServerApp']['StopTunnel']();
}
