/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GameRouteImport } from './routes/_game'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamePlayRouteImport } from './routes/_game/play'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/_game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlayRoute = GamePlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => GameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/rules': typeof RulesRoute
  '/play': typeof GamePlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/rules': typeof RulesRoute
  '/play': typeof GamePlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_game': typeof GameRouteWithChildren
  '/home': typeof HomeRoute
  '/rules': typeof RulesRoute
  '/_game/play': typeof GamePlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home' | '/rules' | '/play'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/rules' | '/play'
  id: '__root__' | '/' | '/_game' | '/home' | '/rules' | '/_game/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRouteWithChildren
  HomeRoute: typeof HomeRoute
  RulesRoute: typeof RulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_game': {
      id: '/_game'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_game/play': {
      id: '/_game/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof GamePlayRouteImport
      parentRoute: typeof GameRoute
    }
  }
}

interface GameRouteChildren {
  GamePlayRoute: typeof GamePlayRoute
}

const GameRouteChildren: GameRouteChildren = {
  GamePlayRoute: GamePlayRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRouteWithChildren,
  HomeRoute: HomeRoute,
  RulesRoute: RulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
